## Biblioteacas
 - importando bilbiotecas que vamos usar

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris

## Carregando base 
 - esta base classifica 3 tipos diferentes de flores iris
 - ela contem como parametros as medicoes das petalas e sepalas
 - o campo target é referente a resposta de qual classe de iris

In [ ]:
base = load_iris() 

print(base.target[[10, 50, 149]]) 
print(list(base.target_names))

[0 1 2]
['setosa', 'versicolor', 'virginica']


In [ ]:
#caso você queira importar um csv da sua base de estudo você pode usa a bibliotea pandas

#import pandas as pd

#base = 'arquivo_da_base.csv'
#df = pd.read_csv(base)
#df.head(10)

## Separando dados de classificação e resposta

In [ ]:
x = base['data']
y = base['target']

y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Separando dados de treino e teste
 - fazemos isso para testar se a nossa maquina conseguiu aprender 
 - separamos 25% dos dados para o teste

In [ ]:
 treino_x, teste_x, treino_y, teste_y = train_test_split(x, y, stratify=y, test_size=0.25)

print("%d dados para treino e %d dados para teste " % (len(treino_x), len(teste_x)))

112 dados para treino e 38 dados para teste 


##Treinando o modelo e analisar percentual de acertos

In [ ]:
modelo = SVC() #instando classificador
modelo.fit(treino_x, treino_y) #metodo treino com os dados de treino

previsao = modelo.predict(teste_x) #metodo predict para classificar os dados de teste
acertos = accuracy_score(previsao, teste_y) * 100 #avaliando as respostas
print("percentual de acetos: %.2f" % acertos + "%")

percentual de acetos: 94.74%


##Fazendo suas proprias predições

In [ ]:
#fazendo suas proprias predicoes

import numpy as np

flores = np.array([[5.1, 3.5, 1.4, 0.2],
       [6.4, 3.2, 4.5, 1.5],
       [6.7, 3.1, 5.6, 2.4]])

previsao = modelo.predict(flores)

print(previsao) #nossa maquina classificou as respostas como setosa, versilicor e virginica

[0 1 2]
