##Importando bibliotecas

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_wine
import numpy as np

##Carregando Base
 - essa base escolida classifica 3 tipos diferentes de vinhos
 - ela usa 12 parametros numericos diferentes
 - é possivel consultar os parametros no site scikit-learn.org

In [2]:
base = load_wine()

print(base.target[[10, 80, 140]])
print(list(base.target_names))

[0 1 2]
['class_0', 'class_1', 'class_2']


## Separando parametros e resposta

In [3]:
x = base['data']
y = base['target']

x

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

##Transformando dados
 - temos uma variezade grande de dados nessa base
 - vamos realizar trasnformações para normalizala
 - assim os classificadores podem ter menos trabalho


In [4]:
from sklearn.preprocessing import StandardScaler

#chamando a funçao de randomização para evitar da ml ter sempre o mesmo percentual de acertos
#np.random.seed(5)

#separando dados
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.25, stratify=y)
print("Separando %d dados para treino e %d dados para teste" %(len(x_treino), len(x_teste)))

scaler = StandardScaler()
scaler.fit(x_treino)
novo_x_treino = scaler.transform(x_treino) #transformando dados de treino
novo_x_teste = scaler.transform(x_teste) #transformando dados de teste

novo_x_treino

Separando 133 dados para treino e 45 dados para teste


array([[-0.07214469,  1.38473517,  1.09334496, ...,  0.29499723,
         1.27267023,  0.0252945 ],
       [ 0.64719375,  0.80843278,  1.3479483 , ..., -0.30439696,
        -0.80211027, -0.73035882],
       [-1.86439469,  1.32984923, -1.92552323, ..., -0.90379115,
         0.26370163, -0.60340906],
       ...,
       [ 0.20827538,  0.06747257,  1.16608877, ...,  0.29499723,
         0.77529134,  1.27967901],
       [ 0.87884511,  3.07705172,  0.36590684, ..., -1.37474373,
        -1.25685668, -0.0653839 ],
       [ 1.64695226, -0.55456811,  1.27520449, ..., -1.67444083,
        -0.94421852, -0.30719296]])

##Classificador SVM linear
 - semelhante a SVM 
 - usa uma metrica de termo linear para se tornar um classificar mais flexivel que o SVM convencional

In [5]:
from sklearn.svm import LinearSVC

modelo = LinearSVC()

modelo.fit(novo_x_treino, y_treino)

previsao = modelo.predict(novo_x_teste)

acertos = accuracy_score(y_teste, previsao) * 100
print("percentual de acertos usando o classificaro LinearSVC: %.2f" % acertos + " %")

percentual de acertos usando o classificaro LinearSVC: 93.33 %


##Classificador Dummy 
 - classificardor simples
 - usa apenas a similaridade numerica entre os parametros

In [6]:
from sklearn.dummy import DummyClassifier

modelo = DummyClassifier()

modelo.fit(novo_x_treino, y_treino)

previsao = modelo.predict(novo_x_teste)

acertos = modelo.score(y_teste, previsao) *100 #perceba que o metodo para medir acurracia no dummy é diferente

print("percentual de acertos usando o classificador dummy: %.2f" % acertos + "%")

percentual de acertos usando o classificador dummy: 24.44%


/usr/local/lib/python3.6/dist-packages/sklearn/dummy.py:132: FutureWarning: The default value of strategy will change from stratified to prior in 0.24.
  "stratified to prior in 0.24.", FutureWarning)


##Arvore de decisão
 - cria uma arvore com varios segmentos 
 - os nós possuem semelhanças entre seus caminhos 

In [7]:
from sklearn.tree import DecisionTreeClassifier

#é preciso setar a pronfundidade maxima da arvore ou ela pode criar um ramo para cada instancia da base
modelo = DecisionTreeClassifier(max_depth = 3)

modelo.fit(novo_x_treino, y_treino)

previsao = modelo.predict(novo_x_teste)

acertos = accuracy_score(y_teste, previsao) * 100

print("percentual de acertos usando arvore de decisao: %.2f" % acertos +" %")

percentual de acertos usando arvore de decisao: 93.33 %
