##Importando bibliotecas

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_wine
import numpy as np

##Carregando Base
 - essa base escolida classifica 3 tipos diferentes de vinhos
 - ela usa 12 parametros numericos diferentes
 - é possivel consultar os parametros no site scikit-learn.org

In [ ]:
base = load_wine()

print(base.target[[10, 80, 140]])
print(list(base.target_names))

[0 1 2]
['class_0', 'class_1', 'class_2']


## Separando parametros e resposta

In [ ]:
x = base['data']
y = base['target']

x

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

##Transformando dados
 - temos uma variezade grande de dados nessa base
 - vamos realizar trasnformações para normalizala
 - assim os classificadores podem ter menos trabalho


In [ ]:
from sklearn.preprocessing import StandardScaler

#chamando a funçao de randomização para evitar da ml ter sempre o mesmo percentual de acertos
#np.random.seed(5)

#separando dados
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.25, stratify=y)
print("Separando %d dados para treino e %d dados para teste" %(len(x_treino), len(x_teste)))

scaler = StandardScaler()
scaler.fit(x_treino)
novo_x_treino = scaler.transform(x_treino) #transformando dados de treino
novo_x_teste = scaler.transform(x_teste) #transformando dados de teste

novo_x_treino

Separando 133 dados para treino e 45 dados para teste


array([[-0.26220191,  0.32209752,  0.55627868, ..., -2.06714871,
        -1.59080461, -0.84878958],
       [ 0.34100421,  1.78179577, -0.29545937, ..., -1.5845061 ,
        -1.46182045,  0.31888036],
       [ 0.21533627,  0.24956593,  0.13040965, ..., -1.5406295 ,
        -1.37583101,  0.33532641],
       ...,
       [ 0.8059756 ,  0.71195482,  0.8660016 , ...,  0.03892811,
         1.1178627 ,  0.35177247],
       [ 2.20088975, -0.53014866,  0.20784038, ...,  1.31134952,
         0.2149736 ,  1.35498185],
       [-0.79000726, -1.03786979, -1.61178181, ...,  0.74095372,
         1.28984157, -0.75011324]])

##Classificador SVM linear
 - semelhante a SVM 
 - usa uma metrica de termo linear para se tornar um classificar mais flexivel que o SVM convencional

In [ ]:
from sklearn.svm import LinearSVC

modelo = LinearSVC()

modelo.fit(novo_x_treino, y_treino)

previsao = modelo.predict(novo_x_teste)

acertos = accuracy_score(y_teste, previsao) * 100
print("percentual de acertos usando o classificaro LinearSVC: %.2f" % acertos + " %")

percentual de acertos usando o classificaro LinearSVC: 97.78 %


##Classificador Dummy 
 - classificardor simples
 - usa apenas a similaridade numerica entre os parametros

In [ ]:
from sklearn.dummy import DummyClassifier

modelo = DummyClassifier()

modelo.fit(novo_x_treino, y_treino)

previsao = modelo.predict(novo_x_teste)

acertos = modelo.score(y_teste, previsao) *100 #perceba que o metodo para medir acurracia no dummy é diferente

print("percentual de acertos usando o classificador dummy: %.2f" % acertos + "%")

percentual de acertos usando o classificador dummy: 15.56%


/usr/local/lib/python3.6/dist-packages/sklearn/dummy.py:132: FutureWarning: The default value of strategy will change from stratified to prior in 0.24.
  "stratified to prior in 0.24.", FutureWarning)


##Arvore de decisão
 - cria uma arvore com varios segmentos 
 - os nós possuem semelhanças entre seus caminhos 

In [ ]:
from sklearn.tree import DecisionTreeClassifier

#é preciso setar a pronfundidade maxima da arvore ou ela pode criar um ramo para cada instancia da base
modelo = DecisionTreeClassifier(max_depth = 3)

modelo.fit(novo_x_treino, y_treino)

previsao = modelo.predict(novo_x_teste)

acertos = accuracy_score(y_teste, previsao) * 100

print("percentual de acertos usando arvore de decisao: %.2f" % acertos +" %")